ViewableImpression wrapper + typo doc
dailymotion/vast-client-js pull request #395
Opened 2021-07-16 13:59 UTC by PaulineMDaily

### Description

As of right now, when the ViewableImpression data is in a Wrapper we are not using the information. VAST 4.2 spec indicates that this should be possible to have ViewableImpression in Wrapper. 
### Issue

https://github.com/dailymotion/vast-client-js/issues/378

### Type
- [ ] Breaking change
- [ ] Enhancement
- [ X ] Fix
- [ ] Documentation
- [ ] Tooling

2021-08-24 14:20 UTC, ZacharieTFR requested changes

2021-08-24 14:20 UTC, ZacharieTFR commented on src/parser/ad_parser.js
> +        ad.viewableImpression = [_parseViewableImpression(node)];
As we initialized the ad object with an empty array for viewableImpression we can do the same as l.183

2021-08-24 15:41 UTC, clementFrancon approved these changes
Same comment as @ZacharieTFR about the push otherwise LGTM

2021-09-03 11:54 UTC, ZacharieTFR approved these changes

2021-09-07 11:57 UTC, merged