Fix issues/483 and add a basic Node example
dailymotion/vast-client-js pull request #484
Opened 2024-11-26 18:33 UTC by nicolaslevy

### Description

* Fixes issues described in https://github.com/dailymotion/vast-client-js/issues/483 
* Add a Node example 
 
### Issue

https://github.com/dailymotion/vast-client-js/issues/483 

### Type
- [ ] Breaking change
- [ ] Enhancement
- [x] Fix
- [ ] Documentation
- [x] Tooling

2024-12-17 15:13 UTC, ZacharieTFR requested changes
Hello, thank you for your contribution, it is much appreciated! I've left a few comments

2024-12-17 15:13 UTC, ZacharieTFR commented on dist/chunks/xmldom-623c1b6b.min.js
Please do not push the dist, we will do it during the next release 😉

2024-12-17 15:13 UTC, ZacharieTFR commented on examples/node/package.json
> +  "description": ""
Lets re-use the same information than the root package
```suggestion
  "name": "VASTClient-node-example",
  "version": "1.0.0",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Dailymotion <vast-client@dailymotion.com> (https://developer.dailymotion.com/)"
  "license": "MIT",
  "description": "VAST Client node usage example"
```

2024-12-17 21:03 UTC, nicolaslevy commented on dist/chunks/xmldom-623c1b6b.min.js
:sweat_smile: done in https://github.com/dailymotion/vast-client-js/pull/484/commits/f910ea0e3a9acf69aac74f43cf4b8528bc4fa7b1

2024-12-17 21:06 UTC, nicolaslevy commented
Thank you @ZacharieTFR, I made those changes

2024-12-17 21:11 UTC, nicolaslevy commented on dist/chunks/xmldom-623c1b6b.min.js
oh... my bad, I deleted them :P Let me restore the original dist folder

2024-12-17 21:15 UTC, nicolaslevy commented on dist/chunks/xmldom-623c1b6b.min.js
Yeap, now the dist folder has no changes. Solved in commit https://github.com/dailymotion/vast-client-js/pull/484/commits/2b48c61d6eac59164e400ef689255c64a2f11f6b

2024-12-18 13:36 UTC, ZacharieTFR reviewed
As you moved the example folder and added the node, can you update the readme aswell ? 
https://github.com/dailymotion/vast-client-js/blob/d6420de113cfd8180cc943e0079e9f2c20374436/README.md?plain=1#L18

2024-12-18 13:36 UTC, ZacharieTFR commented on examples/node/index.js
> +await parseSimpleInline();
The EOF is missing 
```suggestion
await parseSimpleInline();

```

2024-12-18 14:06 UTC, nicolaslevy commented
> As you moved the example folder and added the node, can you update the readme aswell ?
> 
> https://github.com/dailymotion/vast-client-js/blob/d6420de113cfd8180cc943e0079e9f2c20374436/README.md?plain=1#L18

I changed this text in the last commit:
> To explore a practical example of how the VAST client can be implemented in web applications please visit this [link](https://githubbox.com/dailymotion/vast-client-js/tree/master/examples/web). Additionally, use this [link](https://githubbox.com/dailymotion/vast-client-js/tree/master/examples/node) to learn how to use the VAST client in a basic Node application.

@ZacharieTFR  Let me know what you think.

2024-12-18 14:42 UTC, ZacharieTFR approved these changes
LGTM !

2024-12-18 14:56 UTC, nicolaslevy commented
Awesome!! just FYI: we are using this library in this project https://github.com/montevideo-tech/vast-2-sgai/ .A  basic VAST-2-SGAI (VAST to Asset List and ListMPD) opens-ource microservice :)

2025-01-30 13:49 UTC, merged